package com.huanshankeji.team.gitversioning

import com.huanshankeji.github.packages.maven.githubPackagesSetUrlAndCredentials
import com.huanshankeji.gitlab.packageregistry.maven.GITLAB_COM_HOST
import com.huanshankeji.gitlab.packageregistry.maven.gitlabPackageRegistrySetUrlAndCredentials
import com.huanshankeji.team.HUANSHANKEJI_IN_LOWERCASE
import org.gradle.api.artifacts.dsl.RepositoryHandler
import org.gradle.api.artifacts.repositories.MavenArtifactRepository
import org.gradle.api.provider.ProviderFactory
import java.net.URI

// fully generated by AI agent and not reviewed yet

/**
 * Composable DSL for settings.gradle.kts after applying
 * `com.huanshankeji.team.gitversioning.maven-repository-settings-conventions`.
 */
open class HuanshankejiMavenRepositoriesExtension {
    internal lateinit var repositories: RepositoryHandler
    internal lateinit var providers: ProviderFactory
    internal lateinit var uri: (Any) -> URI

    fun huanshankejiMavenLocal(configure: MavenArtifactRepository.() -> Unit = {}) {
        repositories.mavenLocal {
            content {
                contentIncludeHuanshankejiDevCommitVersions()
                contentIncludeHuanshankejiDirtyAndLegacySnapshots()
            }
            configure()
        }
    }

    fun gitlabProjectEndpoint(
        projectId: String,
        nameSuffix: String = projectId,
        configure: MavenArtifactRepository.() -> Unit = {},
    ) {
        context(providers, uri) {
            repositories.maven {
                gitlabPackageRegistrySetUrlAndCredentials(
                    "GitLab-$nameSuffix",
                    providers.provider { "https://$GITLAB_COM_HOST/api/v4/projects/$projectId/packages/maven" },
                )
                configure()
            }
        }
    }

    fun githubPackagesForDevCommits(
        vararg repositoryNames: String,
        owner: String = HUANSHANKEJI_IN_LOWERCASE,
        configure: MavenArtifactRepository.(repositoryName: String) -> Unit = {},
    ) {
        for (repositoryName in repositoryNames) {
            context(providers, uri) {
                repositories.maven {
                    githubPackagesSetUrlAndCredentials(
                        providers.provider { owner },
                        providers.provider { repositoryName },
                    )
                    content {
                        contentIncludeHuanshankejiDevCommitVersions()
                    }
                    configure(repositoryName)
                }
            }
        }
    }

    fun mavenCentral(configure: MavenArtifactRepository.() -> Unit = {}) {
        repositories.mavenCentral(configure)
    }

    fun mavenCentralExcludingHuanshankejiNonStable() {
        mavenCentral {
            contentExcludeHuanshankejiNonStableVersions()
        }
    }

    fun google() {
        repositories.google()
    }
}
