package com.huanshankeji.team.gitversioning

// fully generated by AI agent and not reviewed yet

val extension = extensions.create(
    "huanshankejiMavenRepositories",
    HuanshankejiMavenRepositoriesExtension::class.java,
)

@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
    repositories {
        extension.repositories = this
        extension.providers = providers
        extension.uri = { uri(it) }
    }
}
