package com.huanshankeji.team.gitversioning

import com.huanshankeji.github.packages.maven.githubPackagesSetUrlAndCredentials
import com.huanshankeji.team.HUANSHANKEJI_IN_LOWERCASE
import org.gradle.api.artifacts.dsl.RepositoryHandler
import org.gradle.api.artifacts.repositories.MavenArtifactRepository
import org.gradle.api.provider.ProviderFactory
import java.net.URI

// fully generated by AI agent and not reviewed yet

/**
 * Composable DSL for public OSS repos. No repositories are added unless explicitly configured
 * in `settings.gradle.kts` after applying the settings plugin.
 */
open class PublicOpenSourceDependencyRepositoriesExtension {
    internal lateinit var repositories: RepositoryHandler
    internal lateinit var providers: ProviderFactory
    internal lateinit var uri: (Any) -> URI

    fun huanshankejiMavenLocal() {
        repositories.mavenLocal {
            content {
                contentIncludeHuanshankejiDevCommitVersions()
                contentIncludeHuanshankejiDirtyAndLegacySnapshots()
            }
        }
    }

    fun githubPackages(vararg repositoryNames: String, owner: String = HUANSHANKEJI_IN_LOWERCASE) {
        for (repositoryName in repositoryNames) {
            context(providers, uri) {
                repositories.maven {
                    githubPackagesSetUrlAndCredentials(
                        providers.provider { owner },
                        providers.provider { repositoryName }
                    )
                    content {
                        contentIncludeHuanshankejiDevCommitVersions()
                    }
                }
            }
        }
    }

    fun mavenCentral(configure: MavenArtifactRepository.() -> Unit = {}) {
        repositories.mavenCentral(configure)
    }

    fun mavenCentralExcludingHuanshankejiNonStable() {
        mavenCentral {
            contentExcludeHuanshankejiNonStableVersions()
        }
    }

    fun google() {
        repositories.google()
    }
}
