package com.huanshankeji.git

import org.gradle.api.provider.Provider
import org.gradle.api.provider.ProviderFactory

// Generated by AI agent. Also checked again with AI agent that there are no simpler ways to achieve these.

fun ProviderFactory.gitCommitHash(): Provider<String> =
    exec {
        commandLine("git", "rev-parse", "HEAD")
    }.standardOutput.asText.map { it.trim() }

fun ProviderFactory.isGitWorkingTreeDirty(): Provider<Boolean> =
    exec {
        commandLine("git", "status", "--porcelain")
    }.standardOutput.asText.map { it.isNotBlank() }

fun ProviderFactory.gitCurrentBranch(): Provider<String> =
    exec {
        commandLine("git", "rev-parse", "--abbrev-ref", "HEAD")
    }.standardOutput.asText.map { it.trim() }
