package com.huanshankeji.gitversioning

import com.huanshankeji.GradleCommonExperimentalApi
import com.huanshankeji.git.gitCommitHash
import com.huanshankeji.git.isGitWorkingTreeDirty
import com.huanshankeji.git.workflow.isReleaseBranch
import org.gradle.api.provider.Provider
import org.gradle.api.provider.ProviderFactory

// Generated by AI agent. Also checked again with AI agent that there are no simpler ways to achieve these.

fun devCommitVersionString(baseVersion: String, commitHash: String, dirty: Boolean): String =
    if (dirty) "$baseVersion-dev-commit-$commitHash-dirty-SNAPSHOT"
    else "$baseVersion-dev-commit-$commitHash"

fun ProviderFactory.devCommitVersionProvider(baseVersion: String): Provider<String> =
    gitCommitHash().zip(isGitWorkingTreeDirty()) { hash, dirty ->
        devCommitVersionString(baseVersion, hash, dirty)
    }

/**
 * Returns [baseVersion] when [isRelease] is `true`; otherwise a `*-dev-commit-*` version from Git.
 * Prefer an explicit `isRelease` flag in build logic (set `true` on the release branch) over
 * auto-detecting the Git branch.
 */
fun ProviderFactory.devCommitOrReleaseVersionProvider(
    baseVersion: String,
    isRelease: Boolean,
): Provider<String> =
    if (isRelease) provider { baseVersion }
    else devCommitVersionProvider(baseVersion)

/**
 * Returns [baseVersion] on [releaseBranch]; otherwise a `*-dev-commit-*` version from Git.
 * Override with the Gradle property `com.huanshankeji.forceReleaseVersion=true` when needed.
 *
 * This API is currently not recommended under our convention.
 * Prefer [devCommitOrReleaseVersionProvider] with an explicit `isRelease` flag instead.
 */
@GradleCommonExperimentalApi
fun ProviderFactory.projectVersionFromGitProvider(
    baseVersion: String,
    releaseBranch: String = "release",
): Provider<String> {
    val forceRelease = gradleProperty("com.huanshankeji.forceReleaseVersion")
        .map { it.toBoolean() }
        .orElse(false)
    return forceRelease.flatMap { forceRelease ->
        if (forceRelease) provider { baseVersion }
        else isReleaseBranch(releaseBranch).flatMap { isReleaseBranch ->
            devCommitOrReleaseVersionProvider(baseVersion, isReleaseBranch)
        }
    }
}
