package com.huanshankeji.gitversioning

import com.huanshankeji.GradleCommonExperimentalApi
import com.huanshankeji.git.gitCommitHash
import com.huanshankeji.git.isGitWorkingTreeDirty
import com.huanshankeji.git.workflow.isReleaseBranch
import org.gradle.api.provider.Provider
import org.gradle.api.provider.ProviderFactory

// Generated by AI agent. Also checked again with AI agent that there are no simpler ways to achieve these.

fun devCommitVersionString(baseVersion: String, commitHash: String, dirty: Boolean): String =
    if (dirty) "$baseVersion-dev-commit-$commitHash-dirty-SNAPSHOT"
    else "$baseVersion-dev-commit-$commitHash"

fun ProviderFactory.devCommitVersionProvider(baseVersion: String): Provider<String> =
    gitCommitHash().zip(isGitWorkingTreeDirty()) { hash, dirty ->
        devCommitVersionString(baseVersion, hash, dirty)
    }

/**
 * Returns [baseVersion] on [releaseBranch]; otherwise a `*-dev-commit-*` version from Git.
 * Override with the Gradle property `com.huanshankeji.forceReleaseVersion=true` when needed.
 *
 * This API is not recommended now per our convention.
 * You are recommended to always set the version directly explicitly in a release branch.
 * Use [devCommitVersionProvider] directly in a non-release branch instead.
 */
@GradleCommonExperimentalApi
fun ProviderFactory.projectVersionFromGitProvider(
    baseVersion: String,
    releaseBranch: String = "release",
): Provider<String> {
    val forceRelease = gradleProperty("com.huanshankeji.forceReleaseVersion")
        .map { it.toBoolean() }
        .orElse(false)
    return forceRelease.flatMap { forced ->
        if (forced) provider { baseVersion }
        else isReleaseBranch(releaseBranch).flatMap { release ->
            if (release) provider { baseVersion }
            else devCommitVersionProvider(baseVersion)
        }
    }
}
